version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - adanetwork
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - adanetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESSKEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRETKEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - adanetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  consumer:
    build:
      context: .
      dockerfile: ADA.Consumer/Dockerfile
    image: andrehs/ada.consumer
    container_name: consumer
    environment:
      - CONNECTIONSTRINGS_REDIS=${CONNECTIONSTRINGS_REDIS}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
      - redis
    networks:
      - adanetwork

  producer:
    build:
      context: .
      dockerfile: ADA.Producer/Dockerfile
    image: andrehs/ada.producer
    container_name: producer
    environment:
      - CONNECTIONSTRINGS_REDIS=${CONNECTIONSTRINGS_REDIS}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESSKEY=${MINIO_ACCESSKEY}
      - MINIO_SECRETKEY=${MINIO_SECRETKEY}
      - MINIO_ISSECURE=${MINIO_ISSECURE}
      - MINIO_PORT=${MINIO_PORT}
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - rabbitmq
      - redis
      - minio
    networks:
      - adanetwork

volumes:
  rabbitmq_data:
  redis_data:
  minio_data:

networks:
  adanetwork:
